trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: ls -R
  displayName: 'List all files and directories'

- task: Maven@4
  inputs:
    mavenPomFile: 'Cucumber_Java_selenium/Java_Bdd_selenium4/pom.xml'
    goals: 'clean verify build'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Regression_pipeline'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
